source 'https://api.berkshelf.com'

cookbook 'chef-solo-search', github: 'edelight/chef-solo-search'
cookbook 'git'
cookbook 'ssh-import-id', github: 'adamkrone/chef-ssh-import-id'
cookbook 'capistrano-base', github: 'adamkrone/chef-capistrano-base'
cookbook 'capistrano-wordpress', github: 'adamkrone/chef-capistrano-wordpress'
#cookbook 'wordpress-cluster', github: 'adamkrone/chef-wordpress-cluster'
cookbook 'wordpress-cluster', path: '../chef-wordpress-cluster'
cookbook 'bedrock', path: 'cookbooks/chef-bedrock'
cookbook 'consul', github: 'johnbellone/consul-cookbook', ref: '553d25f945eb1707db6b863766226d71e0a3c6d8'
cookbook 'consul-services', github: 'adamkrone/chef-consul-services'
cookbook 'consul-template', github: 'adamkrone/chef-consul-template'
