source 'https://api.berkshelf.com'

cookbook 'chef-solo-search', github: 'edelight/chef-solo-search'
cookbook 'git'
cookbook 'ssh-import-id', github: 'adamkrone/chef-ssh-import-id'
cookbook 'capistrano-base', github: 'adamkrone/chef-capistrano-base'
cookbook 'capistrano-wordpress', github: 'adamkrone/chef-capistrano-wordpress'
cookbook 'bedrock1', path: 'cookbooks/chef-bedrock1'
cookbook 'bedrock2', path: 'cookbooks/chef-bedrock2'
cookbook 'consul', github: 'johnbellone/consul-cookbook'
