name             'wordpress-cluster1'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures wordpress-cluster1'
long_description 'Installs/Configures wordpress-cluster1'
version          '0.1.0'

depends 'bedrock1'
depends 'bedrock2'
depends 'csync2'
depends 'lsyncd'
depends 'mysql-cluster'
