name             'bedrock2'
maintainer       'Adam Krone'
maintainer_email 'krone.adam@gmail.com'
license          'Apache v2.0'
description      'Installs/Configures bedrock2'
long_description 'Installs/Configures bedrock2'
version          '0.1.0'

depends 'chef-solo-search'
depends 'apt'
depends 'git'
depends 'unzip'
depends 'ssh-import-id'
depends 'wordpress-cluster'
depends 'consul'
depends 'consul-services'
depends 'consul-template'
